### PR TITLE
Add, replace and use Omni Core 0.0.10 RPC API

### PR DESCRIPTION
**Pull request by dexX7**
This PR adds a bunch of new methods, and updates already existing methods, to access the Omni Core RPC API:

- https://github.com/OmniLayer/omnicore/blob/omnicore-0.0.10/src/omnicore/doc/rpc-api.md

If the RPC is `"omni_getbalance"`, then the corresponding method name is `omniGetBalance()`, if the RPC is `"omni_senddexsell"`, then the method name is `omniSendDExSell()` and so on.

### CODE REVIEW

**Comment by dexX7** [comment]
Note @msgilligan:

This breaks backwards compability with Master Core 0.0.9 due to the new RPCs. If this is an issue, then I'd just add the new methods, and rename the old ones, but leave the actual RPCs untouched (e.g. use `"send_MP"` instead of `"omni_send"`).

We will provide backwards compability in Omni Core for at least one version, but on the other hand, once the new release is out, then 0.0.9 must not be used anymore anyway.

**Comment by msgilligan** [comment]
Great work, @dexX7!

I would like for release 0.3 of OmniJ work with both Omni Core 0.0.9 *and* 0.0.10 as it has been up to this point. I'm also hoping we can release version 0.3 very soon and then start on 0.4 which can use the 0.0.10 RPCs exclusively. I do like that you've changed it to the new method names and the calls won't change between 0.3 and 0.4.

Also, if OmniJ 0.4 requires 0.0.10 doesn't `OmniExtendedClient.java` become unnecessary?

**Comment by dexX7** [comment]
> Also, if OmniJ 0.4 requires 0.0.10 doesn't OmniExtendedClient.java become unnecessary?

It goes back to the question, whether we want to create transactions via RPC, or send raw transactions.

Most `omni_sendXXX` calls are checked in 0.0.10, and the extended client bypasses the restrictions on the RPC layer. For example: `omni_send` throws exceptions, if the property to send doesn't exist, or if the sender has an insufficient balance.

For tests with valid transactions this should usually not matter, but we also need to confirm that the core logic works both ways, and invalid transactions are properly rejected on the lower levels, too.

**Comment by msgilligan** [comment]
I agree that we want to test both ways for the reasons you mention. `OmniExtendedClient.java` was created to package up functionality we had created for tests and to make it available to developers that wanted to programmatically generate those transactions with Omni Core 0.0.9. Once Omni Core 0.0.10 is available they won't need `OmniExtendedClient.java` anymore. 

So maybe all we do is update whatever documentation and move `OmniExtendedClient.java` into a test package.

**Comment by dexX7** [comment]
@msgilligan: what is your current plan to finalize 0.3? To my understanding this PR is on hold, until 0.4 starts, correct? I'll rebase soon~.

**Comment by msgilligan** [comment]
@dexX7 I'm hoping to finalize 0.3 this week.

> If this is an issue, then I'd just add the new methods, and rename the old ones, but leave the actual RPCs untouched (e.g. use "send_MP" instead of "omni_send").

I was hoping you were going to update this PR as described above, then it could be part of an 0.3 release that supports both 0.0.9 and 0.0.10, right?

**Comment by dexX7** [comment]
Oh, my bad, I misunderstood!

I'm going adjust this PR, and use the 0.0.9 RPCs then. :)

**Comment by dexX7** [comment]
Alright @msgilligan: I updated the PR:

- the changes are spread across more than one commit
- the new method names are used
- but the old commands remain
- it's compatible with Master Core 0.0.9

Note: I was careful while renaming everything, and I've tested `./gradlew :omnij-rpc:regTest` with Master Core 0.0.9, and Omni Core 0.0.10, but given the scope of the changes, a second look probably doesn't hurt. :)

**Pull request merged**
