### PR TITLE
Update to bitcoinj-addons v0.0.10

### PR DESCRIPTION
**Pull request by msgilligan**
bitcoinj-addons v0.0.10 is still a -SNAPSHOT version. To build this branch you'll need to check out `master` from bitcoinj-addons and do a `./gradlew install`.

Once bitcoinj-addons v.0.0.10 is released, we'll update, review, and merge this PR.

@dexX7 Check out the cleanup in OmniClient.java.

### CODE REVIEW

**Comment by dexX7** [comment]
Looks good to me, although it's a bit confusing that sometimes the target class for the deserialization is proivded, and sometimes not:
```
send("sendrawtx_MP", Sha256Hash.class, ...)
send("omni_getorderbook", propertyForSale.getValue(), ...)
```

**Comment by msgilligan** [comment]
If the target class is not provided it defaults to `Object`.

I suppose we could use different method names for these two cases if it makes things clearer. That or don't provide the overloaded method without the target class and require users to put `Object.class`.

What do you suggest?

**Comment by msgilligan** [comment]
We still need to define POJOs for some of the `Map` return types and define serializers for PropertyType, CurrencyID, Ecosystem, etc.

**Comment by dexX7** [comment]
Hmm.. using a different name is probably more intuitive.

**Comment by msgilligan** [comment]
I had a weird idea what if we create members/constants for the method names that also indicate the return type. So instead of a string literal `"sendrawtx_MP"` we'd have a member:

    protected def sendrawtx_MP = ["sendrawtx_MP", Sha256Hash.class]

Then we could call 

    send(sendrawtx_MP, params)

J

**Comment by dexX7** [comment]
Alternatively, maybe it would already be better to move the class paramter to the end, basically to hint that it's optional?

> I had a weird idea what if we create members/constants for the method names ...

Hehe. It would be nice to have an overview to see which call returns what, but on the other hand, this is also visible via the actual return type of the call method (e.g. `omniSend`), and it seems kinda extensive to do.

**Comment by msgilligan** [comment]
> maybe it would already be better to move the class paramter to the end, basically to hint that it's optional?

varargs (e.g. `Object... params`) must be the last parameter, so that isn't an option. That's why I switched the order in the first place.

I think there are three serious options:

1. Make the parameter mandatory.
2. Have two different names for the method. I've been trying to come up with something that is short and descriptive and haven't some up with something.  The obvious (too) long ones are `sendWithDefaultResultType()` and `sendWithResultType()`. Maybe "call" makes more sense then "send". So one could be just `call()` and the other `callxxx()` -- but I can't come up with a good name for `xxx`.
3. Maybe we can leave it as is. The important thing is that users of the API will be calling `sendToAddress()` etc and that the implementation of each method is down to one line in most cases.

**Comment by dexX7** [comment]
> must be the last parameter, so that isn't an option

Ah, I hoped this wasn't the case and varargs were not "greedy".

I think (1) would be too restricting (e.g. quick tests etc.); I'm fine with (2) or (3). For simplicity we can just leave it for now. This was a minor NIT anyway. :)

**Comment by msgilligan** [comment]
There may also be a better solution that we haven't thought of yet.

**Comment by dexX7** [comment]
As a quick note regarding Travis CI: there is a "circle with arrow" icon, when viewing a job, which can be used to restart the build. Alternatively force-pushing triggers it, too.

It's even possible to block merges, if a build failed, although this could be a bit annoying, but see:

- https://github.com/bitcoin/bitcoin/issues/6697#issuecomment-141639946
- https://github.com/OmniLayer/omnicore/issues/245

**Comment by msgilligan** [comment]
The build is failing because bitcoinj-addons-0.0.10-SNAPSHOT is unavailable to the Travis build.

**Pull request merged**
