### PR TITLE
Replace generate() with generateBlock(1) in regTests

### PR DESCRIPTION
**Pull request by msgilligan**
(another cherry-pick from the current branch of PR #178 )

### CODE REVIEW

**Comment by dexX7** [comment]
Is this still backwards compatible with older versions of Omni Core?

**Comment by msgilligan** [comment]
> Is this still backwards compatible with older versions of Omni Core?

As long as they are based on Bitcoin Core 0.13.0 or later, it should be compatible. That's when `generatetoaddress` was added.

**Comment by dexX7** [comment]
I probably missed a previous commit, but which RPC is used as underlying? Is generateBlocks(i) a wrapper for generatetoaddress?

**Comment by msgilligan** [comment]
> Is generateBlocks(i) a wrapper for generatetoaddress?

Yes, it's a wrapper in `BitcoinExtendedClient.java`: https://github.com/ConsensusJ/consensusj/blob/d1f8c266da0945e9c63583351eb0a11d5407647c/cj-btc-jsonrpc/src/main/java/com/msgilligan/bitcoinj/rpc/BitcoinExtendedClient.java#L112-L114

The change was in this ConsensusJ PR: https://github.com/ConsensusJ/consensusj/pull/60

**Comment by dexX7** [comment]
Thanks!

**Pull request merged**
