### PR TITLE
Ignore currently broken tests

### PR DESCRIPTION
**Pull request by msgilligan**
This PR will ignore the tests that are currently broken by PR #182

### CODE REVIEW

**Comment by dexX7** [comment]
I'm not sure what the benefit of not seeing failing tests would be.

Shouldn't we let them fail, so we can also see, when we fix the underlying issue?

**Comment by msgilligan** [comment]
> I'm not sure what the benefit of not seeing failing tests would be.
> 
> Shouldn't we let them fail, so we can also see, when we fix the underlying issue?

I want to release v0.5.10 because Omni Market Cap needs it. If any tests fail, I can't do a normal release. It also stops us from running CI tests on any other changes that we make to OmniJ.

So what I recommend we do is create a branch with these tests re-enabled and work on fixing the remaining two issues (Issue #184 and Issue #185) on that branch. We could even update the Omni Core pull tester to use this new branch.

**Comment by dexX7** [comment]
@msgilligan: just to clarify, currently these tests only fail with the experimental 0.20 port or also with the proper release?

**Comment by msgilligan** [comment]
> @msgilligan: just to clarify, currently these tests only fail with the experimental 0.20 port or also with the proper release?

They fail with Omni Core 0.8.2 -- which is what is being used on Travis currently.

**Comment by msgilligan** [comment]
We can remove 1675c216f7130ce5a966e2503ac16ab45896f8ba from this PR and resubmit.

**Comment by msgilligan** [comment]
With PR #188 and PR #189 we have better solutions than `@Ignore`-ing.

**Pull request closed without merging**
